services:
  nginx:
    image: nginx:alpine
    container_name: banking-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/containers/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      php:
        condition: service_healthy
        restart: true

  php:
    container_name: banking-php
    build:
      context: .
      dockerfile: ./docker/images/php/Dockerfile
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 | grep pong || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
